#!/bin/python3

import math
import os
import random
import re
import sys


# Time complexity -> O(n)
# Space complexity -> O(n)

def pangrams(s):
    # Write your code here
    s = s.replace(" ", "").lower()
    hashmap = {}
    for chr in s:
        if chr in hashmap:
            continue
        else:
            hashmap[chr] = True
    return 'pangram' if len(hashmap) == 26 else "not pangram"
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
